name: Crypto ETL Auto-Run

on:
  schedule:
    - cron: '0 * * * *'  # Esto significa: Corre cada hora en punto (minuto 0)
  workflow_dispatch:      # Esto te permite picarle a un botón para correrlo manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código de GitHub
        uses: actions/checkout@v3

      - name: Configurar Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar librerías necesarias
        run: pip install requests supabase

      - name: Ejecutar el script de datos
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python etl_nube.py